// <auto-generated />
namespace WebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class firstCreataeDatabase1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstCreataeDatabase1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105291113586_firstCreataeDatabase1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
