// <auto-generated />
namespace WebApplication3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class firstCreateDatabase2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstCreateDatabase2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105282145048_firstCreateDatabase2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
